// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBD-z1Oh4E-TRAdwXYORb_Xbi1xquZeXA',
    appId: '1:619090479228:web:46d4d2d0b00a93084621f9',
    messagingSenderId: '619090479228',
    projectId: 'slink-d689c',
    authDomain: 'slink-d689c.firebaseapp.com',
    storageBucket: 'slink-d689c.appspot.com',
    measurementId: 'G-BLXCQ123JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALQvJLXEAR3quPTsD-c09-S9AuVp3tA10',
    appId: '1:619090479228:android:c8c567065408ae324621f9',
    messagingSenderId: '619090479228',
    projectId: 'slink-d689c',
    storageBucket: 'slink-d689c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJWhPNNKxnMkbbZLNBHQY-EwpjY3WBPPg',
    appId: '1:619090479228:ios:3c85de30538fbcc94621f9',
    messagingSenderId: '619090479228',
    projectId: 'slink-d689c',
    storageBucket: 'slink-d689c.appspot.com',
    iosBundleId: 'com.example.slink',
  );
}
